SET MODE MYSQL;

CREATE SCHEMA IF NOT EXISTS TESTDB;

--App Tables
CREATE TABLE IF NOT EXISTS USER
(
    USER_ID VARCHAR(255) PRIMARY KEY,
    USERNAME VARCHAR(255) not null,
    PASSWORD VARCHAR(255) not null
);

CREATE TABLE IF NOT EXISTS COLLECTION
(
    COLLECTION_ID INT PRIMARY KEY auto_increment,
    USER_ID VARCHAR(255) not null
);

