SET MODE MYSQL;

CREATE SCHEMA IF NOT EXISTS TESTDB;

--App Tables
CREATE TABLE IF NOT EXISTS USER
(
    USER_ID VARCHAR(255) PRIMARY KEY,
    USERNAME VARCHAR(255) not null,
    PASSWORD VARCHAR(255) not null
);

CREATE TABLE IF NOT EXISTS LIBRARY
(
    LIBRARY_ID INT PRIMARY KEY auto_increment,
    LIBRARY_NAME VARCHAR(255) not null,
    USER_ID VARCHAR(255) not null
);

